### PR TITLE
W&B: Add usage in the docs

### PR DESCRIPTION
**Pull request by AyushExel**
- [x] I have marked all applicable categories:
    + [ ] exception-raising fix
    + [ ] algorithm implementation fix
    + [x] documentation modification
    + [ ] new feature
- [ ] I have reformatted the code using `make format` (**required**)
- [ ] I have checked the code using `make commit-checks` (**required**)
- [ ] If applicable, I have mentioned the relevant/related issue(s)
- [ ] If applicable, I have listed every items in this Pull Request below

@Trinkle23897 I've added the usage in the docs. Can you also add something in the readme along with tensorboardLogger?

### CODE REVIEW

**Comment by Trinkle23897** [comment]
> Can you also add something in the readme along with tensorboardLogger?

Could you please give me some suggestions?

**Comment by AyushExel** [comment]
> > Can you also add something in the readme along with tensorboardLogger?
> 
> Could you please give me some suggestions?

After `define hyperparameters` section, you could add a `Logging` section which shows example of initializing both `WandbLogger` and `TensorboardLogger`

**Comment by Trinkle23897** [comment]
I'll try to make it. (Before Saturday... I have a paper submission deadline today)

**Comment by AyushExel** [comment]
@Trinkle23897 Sure. There is no rush. Please take your time.

**Review by Trinkle23897 — APPROVED** [review]

**Pull request merged**
